Fix race condition. This was spotted by Petr Hosek. Thanks Petr!
We were closing stdin from an asynchronous event
handler. This is dangerous because we really don't know when this
handler will be called and in fact when using lit to run symbooglix in
parallel it caused the following scenario to happen

1. doQuery()
- Call PrintCheckSat()

2. Event handler interruption OutputHandler(), receives "sat|...", we close
stdin

3. Event handler called again (OutputHandler), receives "" (empty string),
we try to close stdin again

4. Control returns to somewhere in PrintCheckSat() or above in the call stack
and somewhere in the code it continues to try and use stdin even though we've
closed it.

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at System.IO.StreamWriter.FlushCore () [0x00018] in /build/mono/src/mono-3.2.8/mcs/class/corlib/System.IO/StreamWriter.cs:204
  at System.IO.StreamWriter.Write (System.Char[] buffer) [0x00022] in /build/mono/src/mono-3.2.8/mcs/class/corlib/System.IO/StreamWriter.cs:390
  at System.IO.TextWriter.WriteLine () [0x00000] in /build/mono/src/mono-3.2.8/mcs/class/corlib/System.IO/TextWriter.cs:257
  at System.IO.TextWriter.WriteLine (System.String value) [0x00007] in /build/mono/src/mono-3.2.8/mcs/class/corlib/System.IO/TextWriter.cs:317
  at symbooglix.SMTLIBQueryPrinter.printCheckSat () [0x00011] in /home/dsl11/dev/symbooglix/symbooglix/symbooglix/symbooglix/Expr/SMTLIBQueryPrinter.cs:183
  at symbooglix.Solver.SimpleSMTLIBSolver.doQuery (Microsoft.Boogie.Expr QueryToPrint) [0x00093] in /home/dsl11/dev/symbooglix/symbooglix/symbooglix/symbooglix/Core/Solver/SimpleSMTLIBSolver.cs:109
  at symbooglix.Solver.SimpleSMTLIBSolver.IsQuerySat (Microsoft.Boogie.Expr Query) [0x00003] in /home/dsl11/dev/symbooglix/symbooglix/symbooglix/symbooglix/Core/Solver/SimpleSMTLIBSolver.cs:74
  at symbooglix.Executor.enterProcedure (Microsoft.Boogie.Implementation Impl, System.Collections.Generic.List`1 procedureParams, symbooglix.Executor executor) [0x00273] in /home/dsl11/dev/symbooglix/symbooglix/
symbooglix/symbooglix/Core/Executor.cs:374
  at symbooglix.Executor.run (Microsoft.Boogie.Implementation entryPoint) [0x00035] in /home/dsl11/dev/symbooglix/symbooglix/symbooglix/symbooglix/Core/Executor.cs:195
  at symbooglix.driver.Main (System.String[] args) [0x002af] in /home/dsl11/dev/symbooglix/symbooglix/symbooglix/symbooglix/driver.cs:209