Completed initial implementation of SimpleSMTLIBSolver. It seems a little buggy sometimes. The test feasible_ensures.bpl and sometimes
sometimes fails with

System.NullReferenceException: Object reference not set to an instance of an object
  at System.IO.StreamWriter.FlushCore () [0x00018] in /build/mono/src/mono-3.2.8/mcs/class/corlib/System.IO/StreamWriter.cs:204
  at System.IO.StreamWriter.Write (System.Char[] buffer) [0x00022] in /build/mono/src/mono-3.2.8/mcs/class/corlib/System.IO/StreamWriter.cs:390
  at System.IO.TextWriter.WriteLine () [0x00000] in /build/mono/src/mono-3.2.8/mcs/class/corlib/System.IO/TextWriter.cs:257
  at System.IO.TextWriter.WriteLine (System.String value) [0x00007] in /build/mono/src/mono-3.2.8/mcs/class/corlib/System.IO/TextWriter.cs:317
  at symbooglix.SMTLIBQueryPrinter.printCheckSat () [0x00011] in /home/dan/dev/symbooglix/symbooglix/symbooglix/symbooglix/Expr/SMTLIBQueryPrinter.cs:183
  at symbooglix.Solver.SimpleSMTLIBSolver.doQuery (Microsoft.Boogie.Expr QueryToPrint) [0x00079] in /home/dan/dev/symbooglix/symbooglix/symbooglix/symbooglix/Core/Solver/SimpleSMTLIBSolver.cs:107
  at symbooglix.Solver.SimpleSMTLIBSolver.IsQuerySat (Microsoft.Boogie.Expr Query) [0x00003] in /home/dan/dev/symbooglix/symbooglix/symbooglix/symbooglix/Core/Solver/SimpleSMTLIBSolver.cs:73
  at symbooglix.Executor.enterProcedure (Microsoft.Boogie.Implementation Impl, System.Collections.Generic.List`1 procedureParams, symbooglix.Executor executor) [0x00273] in /home/dan/dev/symbooglix/symbooglix/symbooglix/symbooglix/Core/Executor.cs:374
  at symbooglix.Executor.run (Microsoft.Boogie.Implementation entryPoint) [0x00035] in /home/dan/dev/symbooglix/symbooglix/symbooglix/symbooglix/Core/Executor.cs:195
  at symbooglix.driver.Main (System.String[] args) [0x002af] in /home/dan/dev/symbooglix/symbooglix/symbooglix/symbooglix/driver.cs:210

and sometimes...

Unhandled Exception:
System.ObjectDisposedException: The object was used after being disposed.
  at System.IO.StreamWriter.CheckState () [0x00031] in /build/mono/src/mono-3.2.8/mcs/class/corlib/System.IO/StreamWriter.cs:418
  at System.IO.StreamWriter.Flush () [0x00000] in /build/mono/src/mono-3.2.8/mcs/class/corlib/System.IO/StreamWriter.cs:194
  at symbooglix.SMTLIBQueryPrinter.printCheckSat () [0x00021] in /home/dan/dev/symbooglix/symbooglix/symbooglix/symbooglix/Expr/SMTLIBQueryPrinter.cs:184
  at symbooglix.Solver.SimpleSMTLIBSolver.doQuery (Microsoft.Boogie.Expr QueryToPrint) [0x00079] in /home/dan/dev/symbooglix/symbooglix/symbooglix/symbooglix/Core/Solver/SimpleSMTLIBSolver.cs:107
  at symbooglix.Solver.SimpleSMTLIBSolver.IsQuerySat (Microsoft.Boogie.Expr Query) [0x00003] in /home/dan/dev/symbooglix/symbooglix/symbooglix/symbooglix/Core/Solver/SimpleSMTLIBSolver.cs:73
  at symbooglix.Executor.enterProcedure (Microsoft.Boogie.Implementation Impl, System.Collections.Generic.List`1 procedureParams, symbooglix.Executor executor) [0x00273] in /home/dan/dev/symbooglix/symbooglix/symbooglix/symbooglix/Core/Executor.cs:374
  at symbooglix.Executor.run (Microsoft.Boogie.Implementation entryPoint) [0x00035] in /home/dan/dev/symbooglix/symbooglix/symbooglix/symbooglix/Core/Executor.cs:195
  at symbooglix.driver.Main (System.String[] args) [0x002af] in /home/dan/dev/symbooglix/symbooglix/symbooglix/symbooglix/driver.cs:210
[ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: The object was used after being disposed.